import { AppTheme, ThemeColors } from '../models/types';

const classicColors: ThemeColors = {
  primary: '#2196F3',
  secondary: '#1976D2',
  background: '#FAFAFA',
  surface: '#FFFFFF',
  text: '#212121',
  textSecondary: '#757575',
  accent: '#FF9800',
  error: '#F44336',
  success: '#4CAF50',
  gridLine: '#BDBDBD',
  gridLineThick: '#424242',
  cellBackground: '#FFFFFF',
  cellSelected: '#BBDEFB',
  cellHighlight: '#E3F2FD',
  cellConflict: '#FFCDD2',
  cellFixed: '#F5F5F5',
  numberFixed: '#212121',
  numberUser: '#1976D2',
  numberError: '#D32F2F',
  noteText: '#9E9E9E',
};

const darkColors: ThemeColors = {
  primary: '#64B5F6',
  secondary: '#42A5F5',
  background: '#121212',
  surface: '#1E1E1E',
  text: '#FFFFFF',
  textSecondary: '#B0B0B0',
  accent: '#FFB74D',
  error: '#EF5350',
  success: '#66BB6A',
  gridLine: '#424242',
  gridLineThick: '#B0B0B0',
  cellBackground: '#1E1E1E',
  cellSelected: '#1A237E',
  cellHighlight: '#263238',
  cellConflict: '#4E1A1A',
  cellFixed: '#2C2C2C',
  numberFixed: '#E0E0E0',
  numberUser: '#64B5F6',
  numberError: '#EF5350',
  noteText: '#616161',
};

const oceanColors: ThemeColors = {
  primary: '#00BCD4',
  secondary: '#0097A7',
  background: '#E0F7FA',
  surface: '#FFFFFF',
  text: '#004D40',
  textSecondary: '#00796B',
  accent: '#FF7043',
  error: '#E53935',
  success: '#43A047',
  gridLine: '#80DEEA',
  gridLineThick: '#00695C',
  cellBackground: '#FFFFFF',
  cellSelected: '#B2EBF2',
  cellHighlight: '#E0F7FA',
  cellConflict: '#FFCDD2',
  cellFixed: '#E0F2F1',
  numberFixed: '#004D40',
  numberUser: '#0097A7',
  numberError: '#C62828',
  noteText: '#80CBC4',
};

const sunsetColors: ThemeColors = {
  primary: '#FF7043',
  secondary: '#F4511E',
  background: '#FFF3E0',
  surface: '#FFFFFF',
  text: '#3E2723',
  textSecondary: '#6D4C41',
  accent: '#7C4DFF',
  error: '#D32F2F',
  success: '#388E3C',
  gridLine: '#FFAB91',
  gridLineThick: '#4E342E',
  cellBackground: '#FFFFFF',
  cellSelected: '#FFCCBC',
  cellHighlight: '#FFF3E0',
  cellConflict: '#FFCDD2',
  cellFixed: '#FBE9E7',
  numberFixed: '#3E2723',
  numberUser: '#F4511E',
  numberError: '#B71C1C',
  noteText: '#BCAAA4',
};

const forestColors: ThemeColors = {
  primary: '#66BB6A',
  secondary: '#43A047',
  background: '#E8F5E9',
  surface: '#FFFFFF',
  text: '#1B5E20',
  textSecondary: '#388E3C',
  accent: '#FFC107',
  error: '#E53935',
  success: '#2E7D32',
  gridLine: '#A5D6A7',
  gridLineThick: '#1B5E20',
  cellBackground: '#FFFFFF',
  cellSelected: '#C8E6C9',
  cellHighlight: '#E8F5E9',
  cellConflict: '#FFCDD2',
  cellFixed: '#F1F8E9',
  numberFixed: '#1B5E20',
  numberUser: '#43A047',
  numberError: '#C62828',
  noteText: '#81C784',
};

const midnightColors: ThemeColors = {
  primary: '#7C4DFF',
  secondary: '#651FFF',
  background: '#0D0D1A',
  surface: '#1A1A2E',
  text: '#E8E8E8',
  textSecondary: '#9E9E9E',
  accent: '#FF4081',
  error: '#FF5252',
  success: '#69F0AE',
  gridLine: '#2D2D44',
  gridLineThick: '#7C4DFF',
  cellBackground: '#1A1A2E',
  cellSelected: '#2D1B69',
  cellHighlight: '#1E1E3A',
  cellConflict: '#4E1A2E',
  cellFixed: '#252540',
  numberFixed: '#E8E8E8',
  numberUser: '#B388FF',
  numberError: '#FF5252',
  noteText: '#4A4A6A',
};

export const defaultThemes: AppTheme[] = [
  {
    id: 'classic',
    name: 'Классическая',
    isPremium: false,
    colors: classicColors,
    preview: '#2196F3',
  },
  {
    id: 'dark',
    name: 'Тёмная',
    isPremium: false,
    colors: darkColors,
    preview: '#1E1E1E',
  },
  {
    id: 'ocean',
    name: 'Океан',
    isPremium: true,
    colors: oceanColors,
    preview: '#00BCD4',
  },
  {
    id: 'sunset',
    name: 'Закат',
    isPremium: true,
    colors: sunsetColors,
    preview: '#FF7043',
  },
  {
    id: 'forest',
    name: 'Лес',
    isPremium: true,
    colors: forestColors,
    preview: '#66BB6A',
  },
  {
    id: 'midnight',
    name: 'Полночь',
    isPremium: true,
    colors: midnightColors,
    preview: '#7C4DFF',
  },
];

export function getThemeById(id: string): AppTheme {
  return defaultThemes.find((t) => t.id === id) ?? defaultThemes[0];
}
